page_inspector/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from page_inspector.views import page_details_view

urlpatterns = patterns('',
    url(r'^$', page_details_view),
)

webpage_inspector/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('page_inspector.urls'))
]

page_inspector/models.py
from django.db import models

# Create your models here.

page_inspector/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.validators import URLValidator


class PageInspectorForm(forms.Form):
    url = forms.URLField(label=u'url', validators=[URLValidator])

page_inspector/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from page_inspector.forms import PageInspectorForm
from page_inspector.page_details import PageDetails

def page_details_view(request):
    ctx = {}
    if request.POST:
        form = PageInspectorForm(request.POST)
        if form.is_valid():
            ctx['page_details'] = PageDetails(form.cleaned_data['url'])
    else:
        form = PageInspectorForm()
    ctx['form'] = form
    return render_to_response('index.html', ctx,
                              context_instance=RequestContext(request))

page_inspector/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="col-md-12">
        <div class="row">
            <h1>Enter an URL to get information about the page</h1>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-2"><label for="id_url">URL: </label></div>
                <div class="col-md-5">
                    {{ form.url }}
                </div>
            </div>

            <div class="row">
                <div  class="col-md-5">
                    {% if form.url.errors %}
                    <ul>
                        {% for error in form.url.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {%endif%}
                </div>
            </div>

            <!-- buttons -->
            <div class="row">
                <button class="btn btn-default" type="submit">Get information</button>
            </div>
        </form>

        <!-- page details -->

        {% if page_details %}
        <h2>Page details</h2>
        <div class="row">
            <div class="col-md-2">Title:</div>
            <div class="col-md-10">{{ page_details.page_title }}</div>
        </div>
        <!-- meta tags -->
        <div class="row">
            <div class="col-md-2">Meta tags:</div>
            <div class="col-md-10">
                {% if page_details.meta_tags %}
                <ul>
                    {% for k,v in meta_tags.items %}
                    <li>{{ k }}: {{ v }} </li>
                    {% endfor %}
                </ul>
                {%endif%}
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">Word Count:</div>
            <div class="col-md-10">{{ page_details.word_count }}</div>
        </div>

        <div class="row">
            <div class="col-md-2">Unique words:</div>
            <div class="col-md-10">{{ page_details.unique_words }}</div>
        </div>

        <div class="row">
            <div class="col-md-2">Non unique words:</div>
            <div class="col-md-10">{{ page_details.non_unique_words }}</div>
        </div>

        <div class="row">
            <div class="col-md-2">Most common words:</div>
            <div class="col-md-10">
                {% if page_details.common_words %}
                <ul>
                    {% for word in common_words %}
                    <li>{{ word }}</li>
                    {% endfor %}
                </ul>
                {%endif%}
            </div>
        </div>

        {% endif %}

    </div>
{% endblock%}

webpage_inspector/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Page Inspector</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
</head>
<body>
<div class="container">
{% block content%}{% endblock %}
</div>
</body>
</html>